[package]
name = "rust_pi"
version = "0.1.0"
edition = "2024"

[dependencies]
dashu-int = "0.4.1"
serde = { version = "1.0.228", features = ["derive"] }
ureq = { version = "3.1.2", features = ["json"] }
